
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - test.nailcui.github.io
  resources:
  - nails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.nailcui.github.io
  resources:
  - nails/finalizers
  verbs:
  - update
- apiGroups:
  - test.nailcui.github.io
  resources:
  - nails/status
  verbs:
  - get
  - patch
  - update
